import requests

output_file = open("japanese_translation.py", "w", encoding='utf8')
output_file.write("# DO NOT EDIT MANUALLY. This  file is automatically generated by create_japanese_translation.py\n\n")

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Species_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Species_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/ja/text_Species_ja.txt'
r = requests.get(url, allow_redirects=True)
open('text_Species_ja.txt', 'wb').write(r.content)

species_english_file = open("text_Species_en.txt", "r", encoding='utf8')
species_japanese_file = open("text_Species_ja.txt", "r", encoding='utf8')

species_english_lines = species_english_file.readlines()
species_japanese_lines = species_japanese_file.readlines()

output_file.write("translate_pokemon = {\n")
for i in range(0, len(species_english_lines)):
    output_file.write('\t"{english_string}" : "{japanese_string}",\n'.format(english_string=species_english_lines[i].rstrip("\n"),japanese_string=species_japanese_lines[i].rstrip("\n")))
output_file.write("}\n\n")

species_english_file.close()
species_japanese_file.close()



url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Abilities_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Abilities_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/ja/text_Abilities_ja.txt'
r = requests.get(url, allow_redirects=True)
open('text_Abilities_ja.txt', 'wb').write(r.content)

abilities_english_file = open("text_Abilities_en.txt", "r", encoding='utf8')
abilities_japanese_file = open("text_Abilities_ja.txt", "r", encoding='utf8')

abilities_english_lines = abilities_english_file.readlines()
abilities_japanese_lines = abilities_japanese_file.readlines()

output_file.write("translate_ability = {\n")
for i in range(0, len(abilities_english_lines)):
    output_file.write('\t"{english_string}" : "{japanese_string}",\n'.format(english_string=abilities_english_lines[i].rstrip("\n"),japanese_string=abilities_japanese_lines[i].rstrip("\n")))
# todo hack
output_file.write('\t"Compoundeyes" : "Oeil Compose"\n')
# todo hack
output_file.write("}\n\n")

species_english_file.close()
species_japanese_file.close()



url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Types_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Types_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/ja/text_Types_ja.txt'
r = requests.get(url, allow_redirects=True)
open('text_Types_ja.txt', 'wb').write(r.content)

types_english_file = open("text_Types_en.txt", "r", encoding='utf8')
types_japanese_file = open("text_Types_ja.txt", "r", encoding='utf8')

types_english_lines = types_english_file.readlines()
types_japanese_lines = types_japanese_file.readlines()

output_file.write("translate_type = {\n")
for i in range(0, len(types_english_lines)):
    output_file.write('\t"{english_string}" : "{japanese_string}",\n'.format(english_string=types_english_lines[i].rstrip("\n"),japanese_string=types_japanese_lines[i].rstrip("\n")))
output_file.write('\t"" : ""\n')
output_file.write("}\n\n")

types_english_file.close()
types_japanese_file.close()