import requests

output_file = open("french_translation.py", "w")
output_file.write("# DO NOT EDIT MANUALLY. This  file is automatically generated by create_french_translation.py\n\n")

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Species_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Species_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/fr/text_Species_fr.txt'
r = requests.get(url, allow_redirects=True)
open('text_Species_fr.txt', 'wb').write(r.content)

species_english_file = open("text_Species_en.txt", "r")
species_french_file = open("text_Species_fr.txt", "r")

species_english_lines = species_english_file.readlines()
species_french_lines = species_french_file.readlines()

output_file.write("translate_pokemon = {\n")
for i in range(0, len(species_english_lines)):
    output_file.write('\t"{english_string}" : "{french_string}",\n'.format(english_string=species_english_lines[i].rstrip("\n"),french_string=species_french_lines[i].rstrip("\n")))
output_file.write("}\n\n")

species_english_file.close()
species_french_file.close()



url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Abilities_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Abilities_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/fr/text_Abilities_fr.txt'
r = requests.get(url, allow_redirects=True)
open('text_Abilities_fr.txt', 'wb').write(r.content)

abilities_english_file = open("text_Abilities_en.txt", "r")
abilities_french_file = open("text_Abilities_fr.txt", "r")

abilities_english_lines = abilities_english_file.readlines()
abilities_french_lines = abilities_french_file.readlines()

output_file.write("translate_ability = {\n")
for i in range(0, len(abilities_english_lines)):
    output_file.write('\t"{english_string}" : "{french_string}",\n'.format(english_string=abilities_english_lines[i].rstrip("\n"),french_string=abilities_french_lines[i].rstrip("\n")))
# todo hack
output_file.write('\t"Compoundeyes" : "Oeil Compose"\n')
# todo hack
output_file.write("}\n\n")

species_english_file.close()
species_french_file.close()



url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Types_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Types_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/fr/text_Types_fr.txt'
r = requests.get(url, allow_redirects=True)
open('text_Types_fr.txt', 'wb').write(r.content)

types_english_file = open("text_Types_en.txt", "r")
types_french_file = open("text_Types_fr.txt", "r")

types_english_lines = types_english_file.readlines()
types_french_lines = types_french_file.readlines()

output_file.write("translate_type = {\n")
for i in range(0, len(types_english_lines)):
    output_file.write('\t"{english_string}" : "{french_string}",\n'.format(english_string=types_english_lines[i].rstrip("\n"),french_string=types_french_lines[i].rstrip("\n")))
output_file.write('\t"" : ""\n')
output_file.write("}\n\n")

types_english_file.close()
types_french_file.close()