import requests

output_file = open("spanish_translation.py", "w", encoding='utf8')
output_file.write("# DO NOT EDIT MANUALLY. This  file is automatically generated by create_spanish_translation.py\n\n")

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Species_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Species_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/es/text_Species_es.txt'
r = requests.get(url, allow_redirects=True)
open('text_Species_es.txt', 'wb').write(r.content)

species_english_file = open("text_Species_en.txt", "r", encoding='utf8')
species_spanish_file = open("text_Species_es.txt", "r", encoding='utf8')

species_english_lines = species_english_file.readlines()
species_spanish_lines = species_spanish_file.readlines()

output_file.write("translate_pokemon = {\n")
for i in range(0, len(species_english_lines)):
    output_file.write('\t"{english_string}" : "{spanish_string}",\n'.format(english_string=species_english_lines[i].rstrip("\n"),spanish_string=species_spanish_lines[i].rstrip("\n")))
output_file.write("}\n\n")

species_english_file.close()
species_spanish_file.close()



url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Abilities_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Abilities_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/es/text_Abilities_es.txt'
r = requests.get(url, allow_redirects=True)
open('text_Abilities_es.txt', 'wb').write(r.content)

abilities_english_file = open("text_Abilities_en.txt", "r", encoding='utf8')
abilities_spanish_file = open("text_Abilities_es.txt", "r", encoding='utf8')

abilities_english_lines = abilities_english_file.readlines()
abilities_spanish_lines = abilities_spanish_file.readlines()

output_file.write("translate_ability = {\n")
for i in range(0, len(abilities_english_lines)):
    output_file.write('\t"{english_string}" : "{spanish_string}",\n'.format(english_string=abilities_english_lines[i].rstrip("\n"),spanish_string=abilities_spanish_lines[i].rstrip("\n")))
# todo hack
output_file.write('\t"Compoundeyes" : "Ojo Compuesto"\n')
# todo hack
output_file.write("}\n\n")

species_english_file.close()
species_spanish_file.close()



url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/en/text_Types_en.txt'
r = requests.get(url, allow_redirects=True)
open('text_Types_en.txt', 'wb').write(r.content)

url = 'https://raw.githubusercontent.com/kwsch/PKHeX/master/PKHeX.Core/Resources/text/es/text_Types_es.txt'
r = requests.get(url, allow_redirects=True)
open('text_Types_es.txt', 'wb').write(r.content)

types_english_file = open("text_Types_en.txt", "r", encoding='utf8')
types_spanish_file = open("text_Types_es.txt", "r", encoding='utf8')

types_english_lines = types_english_file.readlines()
types_spanish_lines = types_spanish_file.readlines()

output_file.write("translate_type = {\n")
for i in range(0, len(types_english_lines)):
    output_file.write('\t"{english_string}" : "{spanish_string}",\n'.format(english_string=types_english_lines[i].rstrip("\n"),spanish_string=types_spanish_lines[i].rstrip("\n")))
output_file.write('\t"" : ""\n')
output_file.write("}\n\n")

types_english_file.close()
types_spanish_file.close()