name: Build data files

on: [workflow_dispatch]

jobs:
  package_ball:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Delete files
      run: |
        del data/*.json
        del data/*.pickle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate data
      run: |
        python scripts/package_ball.py
    - uses: actions/upload-artifact@v2
      with:
        name: package_ball
        path: |
          data/ball_sprites.pickle

  package_pokemon:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Delete files
      run: |
        del data/*.json
        del data/*.pickle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate data
      run: |
        python scripts/package_pokemon.py
    - uses: actions/upload-artifact@v2
      with:
        name: package_pokemon
        path: |
          data/rental_pokemon.json
          data/boss_pokemon.json

  score_pokemon:
    runs-on: windows-latest
    needs: package_pokemon

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Delete files
      run: |
        del data/*.json
        del data/*.pickle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/download-artifact@v2
      with:
        name: package_pokemon
        path: data/
    - name: Generate data
      run: |
        python scripts/score_pokemon.py
    - uses: actions/upload-artifact@v2
      with:
        name: score_pokemon
        path: |
          data/boss_matchup_LUT.json
          data/rental_matchup_LUT.json
          data/rental_pokemon_scores.json

  package_pokemon_sprites:
    runs-on: windows-latest
    needs: package_pokemon

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Delete files
      run: |
        del data/*.json
        del data/*.pickle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/download-artifact@v2
      with:
        name: package_pokemon
        path: data/
    - name: Generate data
      run: |
        python scripts/package_pokemon_sprites.py
    - uses: actions/upload-artifact@v2
      with:
        name: package_pokemon_sprites
        path: |
          data/pokemon_sprites.pickle

  get_good_color_discord:
    runs-on: windows-latest
    needs: package_pokemon

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Delete files
      run: |
        del data/*.json
        del data/*.pickle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/download-artifact@v2
      with:
        name: package_pokemon
        path: data/
    - name: Generate data
      run: |
        python scripts/get_good_color_discord.py
    - uses: actions/upload-artifact@v2
      with:
        name: get_good_color_discord
        path: |
          data/boss_colors.json

  build_path_tree:
    runs-on: windows-latest
    needs: package_pokemon

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Delete files
      run: |
        del data/*.json
        del data/*.pickle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/download-artifact@v2
      with:
        name: package_pokemon
        path: data/
    - name: Generate data
      run: |
        python scripts/build_path_tree.py
    - uses: actions/upload-artifact@v2
      with:
        name: build_path_tree
        path: |
          data/path_tree.json

  merge_data:
    runs-on: windows-latest
    needs: score_pokemon

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: package_ball
        path: data/
    - uses: actions/download-artifact@v2
      with:
        name: package_pokemon
        path: data/
    - uses: actions/download-artifact@v2
      with:
        name: score_pokemon
        path: data/
    - uses: actions/download-artifact@v2
      with:
        name: package_pokemon_sprites
        path: data/
    - uses: actions/download-artifact@v2
      with:
        name: get_good_color_discord
        path: data/
    - uses: actions/download-artifact@v2
      with:
        name: build_path_tree
        path: data/
    - uses: actions/upload-artifact@v2
      with:
        name: all_data
        path: |
          data/*